include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/antlr/**"

  errors:
    use_key_in_widget_constructors: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_single_quotes: true
